// <auto-generated />
using System;
using EFCore21.DataSeeding.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EFCore21.DataSeeding.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20180413165346_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore21.DataSeeding.Model.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new { Id = 1, Name = "Entity Framework Team Blog" },
                        new { Id = 2, Name = ".NET Team Blog" }
                    );
                });

            modelBuilder.Entity("EFCore21.DataSeeding.Model.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorName");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("IpAddress");

                    b.Property<int>("PostId");

                    b.Property<string>("Text");

                    b.Property<string>("Type")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new { Id = 1, AuthorName = "Thomas", CreatedDate = new DateTime(2018, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), IpAddress = "218.1.146.14", PostId = 3, Text = "Awesome news!", Type = "Question" },
                        new { Id = 2, AuthorName = "Bill [MSFT]", CreatedDate = new DateTime(2018, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), IpAddress = "199.34.52.20", PostId = 3, Text = "Thank you, we hope this helps.", Type = "General" },
                        new { Id = 3, AuthorName = "Greg", CreatedDate = new DateTime(2018, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), IpAddress = "134.56.2.34", PostId = 1, Text = "Cannot wait til I try it!", Type = "Suggestion" }
                    );
                });

            modelBuilder.Entity("EFCore21.DataSeeding.Model.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlogId");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime?>("PublishedDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new { Id = 1, BlogId = 1, Content = "Today, we are announcing .NET Core 2.1 Preview 2. The release is now ready for broad testing, as we get closer to a final build within the next two to three months. We’d appreciate any feedback that you have. ASP.NET Core 2.1 Preview 2 and Entity Framework 2.1 Preview 2 are also releasing today. You…", PublishedDate = new DateTime(2018, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Announcing Entity Framework Core 2.1 Preview 2" },
                        new { Id = 2, BlogId = 2, Content = "Have you had to design general purpose “metadata” tables in your SQL database that basically store column names and values? Do you often serialize/de-serialize XML or JSON from your SQL tables to handle volatile schemas and data? .NET developers have traditionally worked with relational database management systems (RDMS) like SQL Server. RDMS systems have withstood…", PublishedDate = new DateTime(2018, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Explore CosmosDB with .NET Core and MongoDB" },
                        new { Id = 3, BlogId = 2, Content = "The user interface (UI) of any application is critical in making your app convenient and efficient for the folks using it. When developing applications for Enterprise use, a good UI can shave time off an entire company’s workflow. Visual Studio is investing in new tools to improve the productivity of Windows desktop developers and we’d love your…", PublishedDate = new DateTime(2018, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Calling all Desktop Developers: how should UI development be improved?" },
                        new { Id = 4, BlogId = 2, Content = "Today, we are happy to share an Early Access build with the .NET Framework 4.7.2 Developer Pack. The .NET Framework 4.7.2 Developer Pack lets developers build applications that target the .NET Framework 4.7.2 by using Visual Studio 2017, Visual Studio 2015 or other IDEs. This is a single package that bundles the .NET Framework 4.7.2, the…", PublishedDate = new DateTime(2018, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = ".NET Framework 4.7.2 Developer Pack Early Access build 3056 is available!" }
                    );
                });

            modelBuilder.Entity("EFCore21.DataSeeding.Model.Comment", b =>
                {
                    b.HasOne("EFCore21.DataSeeding.Model.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCore21.DataSeeding.Model.Post", b =>
                {
                    b.HasOne("EFCore21.DataSeeding.Model.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
